[content]
src = "src/"
dist = "dist/"
templates = ["index.html", "updatePlugins.xml"]

[github]
user = "mdklatt"
api = "https://api.github.com"

[[plugins]]
repo = "idea-ansible-plugin"
artifact = "idea-ansible-plugin"

[[plugins]]
repo = "idea-netcdf-plugin"
artifact = "idea-netcdf-plugin"

[[plugins]]
repo = "idea-remotepython-plugin"
artifact = "idea-remotepython-plugin"
