user = "mdklatt"
repo_config = "dist/updatePlugins.xml"

[[plugins]]
repo = "idea-ansible-plugin"
artifact = "idea-ansible-plugin"

[[plugins]]
repo = "idea-netcdf-plugin"
artifact = "idea-netcdf-plugin"

[[plugins]]
repo = "idea-remotepython-plugin"
artifact = "idea-remotepython-plugin"
