# Simple workflow for deploying static content to GitHub Pages
name: Pages

on:
  push:
    branches: ["main"]

  # Allow workflow to be triggered manually from the GitHub UI tab.
  workflow_dispatch:

  # Allow workflow to be triggered by other other workflows.
  # <https://github.blog/2022-02-10-using-reusable-workflows-github-actions>
  # TODO
  workflow_call:


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out project
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: pip
      - name: Install Python dependencies
        run: python -m pip install -U pip -r requirements.txt
      - name: Build content
        run: python build.py
      - name: Set up Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
